export const colorsData = [
  { name: "Black", hex: "#111111" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Ivory", hex: "#FFFFF0" },
  { name: "Off White", hex: "#F5F5F0" },
  { name: "Cream", hex: "#F2E8CF" },
  { name: "Beige", hex: "#E8DCC8" },
  { name: "Sand", hex: "#D8C3A5" },
  { name: "Tan", hex: "#D2B48C" },
  { name: "Camel", hex: "#C19A6B" },
  { name: "Khaki", hex: "#C3B091" },
  { name: "Taupe", hex: "#8B7D6B" },
  { name: "Brown", hex: "#5C4033" },
  { name: "Chocolate", hex: "#3B2519" },
  { name: "Charcoal", hex: "#36454F" },
  { name: "Grey", hex: "#808080" },
  { name: "Light Grey", hex: "#D3D3D3" },
  { name: "Dark Grey", hex: "#4A4A4A" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Navy", hex: "#1B2A4A" },
  { name: "Blue", hex: "#2B4C7E" },
  { name: "Royal Blue", hex: "#2547A0" },
  { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Baby Blue", hex: "#BFE3F0" },
  { name: "Teal", hex: "#0F766E" },
  { name: "Turquoise", hex: "#30D5C8" },
  { name: "Mint", hex: "#98D8C1" },
  { name: "Green", hex: "#2F4538" },
  { name: "Olive", hex: "#556B2F" },
  { name: "Sage", hex: "#9CAF88" },
  { name: "Emerald", hex: "#0B6E4F" },
  { name: "Forest Green", hex: "#228B22" },
  { name: "Lime", hex: "#B7D64A" },
  { name: "Yellow", hex: "#F5D547" },
  { name: "Mustard", hex: "#D4A72C" },
  { name: "Gold", hex: "#C9A227" },
  { name: "Orange", hex: "#E2703A" },
  { name: "Burnt Orange", hex: "#B5502D" },
  { name: "Rust", hex: "#8B3A25" },
  { name: "Coral", hex: "#FF6F5E" },
  { name: "Peach", hex: "#FFCBA4" },
  { name: "Salmon", hex: "#FA8072" },
  { name: "Red", hex: "#7C2D2D" },
  { name: "Wine", hex: "#6E1F27" },
  { name: "Maroon", hex: "#5C1A1B" },
  { name: "Burgundy", hex: "#4A0E1F" },
  { name: "Rose", hex: "#D9A3A9" },
  { name: "Pink", hex: "#F4C2C2" },
  { name: "Hot Pink", hex: "#E0578F" },
  { name: "Blush", hex: "#F1D4D4" },
  { name: "Magenta", hex: "#A02472" },
  { name: "Purple", hex: "#5B3A70" },
  { name: "Lavender", hex: "#C9B6E4" },
  { name: "Lilac", hex: "#D9C6E8" },
  { name: "Plum", hex: "#5D3552" },
  { name: "Mauve", hex: "#9B7E8C" },
  { name: "Denim", hex: "#3B5B7C" },
  { name: "Indigo", hex: "#2C2A4A" },
  { name: "Rose Gold", hex: "#B76E79" },
  { name: "Bronze", hex: "#8C6239" },
  { name: "Copper", hex: "#B36A5E" },
  { name: "Multicolor", hex: "linear-gradient(90deg,#E2703A,#F5D547,#2B4C7E,#7C2D2D)" },
];
 